---
title: "MICE_imputation"
author: "Deron Tsai"
date: "2023-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(mice)
library(tidyverse)
train <- read.csv("../../clean_data/mci_wv1go_aug.csv")
test <- read.csv("../../clean_data/mci_wv23_aug.csv")
```

### Visualization

Overall missing patterns of different waves are quite different. 
I will impute the train & test set seperately to avoid information leakage

```{r}
df_bar <- data.frame(variable=names(train), train=colMeans(is.na(train)), test=colMeans(is.na(test)) ) %>%
  pivot_longer(cols=c("train", "test"), names_to = "set", values_to = "Missingness")
ggplot(df_bar) +
  geom_bar(aes(x=reorder(variable, desc(Missingness)), y=Missingness, fill=set), position="dodge", stat = "identity")+
  xlab("Feature") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
# md.pattern(train, rotate.names = T)
# md.pattern(test, rotate.names = T)
fluxplot(train)
fluxplot(test)
```

### Imputation for training

```{r}
pred = quickpred(train)
imp = mice(train, seed=1, m=5, maxit=5, pred=pred, printFlag = F, ridge=0.001)  
# > # default error: probably due to linear combination according to the warning 
# > set higher ridge to address collinearity
# imp$method    # all use pmm
# diagnostic:
bwplot(imp, layout = c(3, 1))
stripplot(imp, pch = c(21, 20), cex = c(1, 1.5), layout = c(3, 1))
# export:
for (i in 1:5){
  fl <- complete(imp, i)
  fl_name <- paste0("../../clean_data/impute/train", i, ".csv")
  write.csv(fl, file = fl_name, row.names=FALSE)
}
```


### Imputation for testing

```{r}
pred = quickpred(test)
imp = mice(test, seed=1, m=5, maxit=5, pred=pred, printFlag = F, ridge=0.001)  
# > # default error: probably due to linear combination according to the warning 
# > set higher ridge to address collinearity
# imp$method    # all use pmm
# diagnostic:
bwplot(imp, layout = c(3, 1))
stripplot(imp, pch = c(21, 20), cex = c(1, 1.5), layout = c(3, 1))
# export:
for (i in 1:5){
  fl <- complete(imp, i)
  fl_name <- paste0("../../clean_data/impute/test", i, ".csv")
  write.csv(fl, file = fl_name, row.names=FALSE)
}
```

```{r}
pred = quickpred(train)
imp = mice(train, seed=1, m=1, maxit=1, pred=pred, printFlag = F, ridge=0.001)  
check_na = complete(imp, m=3)[[1]]
sum(is.na(check_na))
colSums(is.na(check_na))  
```

